dist: trusty

language: ruby

cache:
  bundler: true

script:
  - bundle exec rake spec

services:
  - redis-server
  - mariadb

rvm:
  - 2.4.2
  - 2.5.1

before_script:
  - sudo apt-get install software-properties-common 
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db 
  - sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu trusty main'
  - sudo apt-get update -y
  - sudo apt-get install mariadb-oqgraph-engine-10.0
  - mysql -u root -e "CREATE DATABASE futurewars_test;"
  - mysql -u root -e "CREATE USER 'futurewars'@'localhost' IDENTIFIED BY 'futurewars';"
  - mysql -u root -e "GRANT ALL ON futurewars_test.* TO 'futurewars'@'localhost';"
  - mysql -u root -e "install plugin oqgraph soname 'ha_oqgraph.so';"
  - bundle exec rake db:migrate RAILS_ENV=test
