dist: trusty

language: ruby

cache:
  bundler: true

script:
  - bundle exec rake test_app
  - bundle exec rake spec

services:
  - redis-server
  - mysql

rvm:
  - 2.4.2
  - 2.5.1

before_script:
  - mysql -u root -e "CREATE DATABASE futurewars_test;"
  - mysql -u root -e "CREATE USER 'futurewars'@'localhost' IDENTIFIED BY 'futurewars';"
  - mysql -u root -e "GRANT ALL ON futurewars_test.* TO 'futurewars'@'localhost';"
  - mysql -u root -e "INSTALL SONAME 'ha_oqgraph'"
